name: Go

on:
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23'

      - name: Get dependencies
        run: |
          go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Generate coverage report
        run: bash go.test.sh -xe

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: coverage.txt
        
