name: Go

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
   
    - name: Set up Go 1.x
      uses: actions/setup-go@v5

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
  
    - name: Build
      run: go build -v main.go

    - name: Generate coverage report
      run: |
        echo "A initial message"
        echo pwd
        echo ls
        bash go.test.sh -xe
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: coverage.txt
        
